schema_version: 1
kind: reap_recipe

name: eaftreap_gptoss20b_keepfrac060_keep19
description: >
  EAFT‑REAP structural prune recipe for GPT‑OSS‑20B with keep_frac=0.60 and
  keep_n=floor(0.60*32)=19 (uniform across layers). No finetune; top_k unchanged.

source:
  manifest_json: harmony/cuda-norm/artifacts/20b_pruned_models_eaftreap_keepfrac/manifest_eaftreap_keepfrac.json
  scores_yaml: harmony/cuda-norm/pruning/recipes/reap-scores_20b_eaftreap_keepfrac060_keep19.yaml

model:
  base_model_id: openai/gpt-oss-20b
  pruned_model_label: calib_union_keep19of32_k59_eaftreap
  keep_frac_requested: 0.60
  keep_n: 19
  num_experts: 32
  uniform_keep_n_across_layers: true
  top_k_unchanged: true
  compatibility_notes:
    - >
      Some SGLang FlashInfer MXFP4 MoE kernels require num_experts % 4 == 0.
      If that constraint is enforced, the “0.60” target becomes keep_n=20/32 (0.625).

profiling_data:
  dataset_repo: radna0/harmony-qwen3-calib-packs-v2-20260113
  sampling:
    strategy: per_file
    num_rows: 5000
    seed: 3407
  max_seq_length: 2048
  batch_size: 30

evaluation:
  gates_json: harmony/cuda-norm/pruning/near_lossless_gates.json
  status: "PENDING (Modal spend-limit blocked)"
  intended_eval_regime:
    seq_lens_csv: "1024,2048"
    num_blocks: 512
    batch_size: 1
    sample_points: 200000
    top_k: 4

execution:
  modal:
    commands:
      - "modal run harmony/cuda-norm/modal/gpt_oss_pruning_track.py --task build_pruned_20b_eaftreap_keepfrac --keep-fracs-csv 0.60 --keep-n-round floor"
      - "env GPU_TYPE=B200:1 modal run harmony/cuda-norm/modal/collect_calib_packs_eaft_single.py --model-id calib_union_keep19of32_k59_eaftreap --model-path <OUT_DIR> --seq-lens-csv 1024,2048 --num-blocks 512 --batch-size 1 --sample-points 200000 --top-k 4"
  kaggle_versa:
    commands:
      - "bash harmony/cuda-norm/scripts/kaggle_run_eaftreap_keepfrac_060.sh"

